-- MySQL Script generated by MySQL Workbench
-- Thu Sep 17 11:07:41 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema personal_management
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema personal_management
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `personal_management` DEFAULT CHARACTER SET utf8 ;
USE `personal_management` ;

-- -----------------------------------------------------
-- Table `personal_management`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `personal_management`.`USUARIO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `primer_nombre` VARCHAR(45) NOT NULL,
  `segundo_nombre` VARCHAR(45) NULL,
  `primer_apellido` VARCHAR(45) NOT NULL,
  `segundo_apellido` VARCHAR(45) NULL,
  `fecha_nacimiento` DATETIME NOT NULL,
  `edad` INT NOT NULL,
  `ciudad_domicilio` VARCHAR(45) NOT NULL,
  `estado` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `personal_management`.`TELEFONO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `personal_management`.`TELEFONO` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero_telefono` VARCHAR(45) NULL,
  `tipo_telefono` VARCHAR(45) NULL,
  `USUARIO_id` INT NOT NULL,
  `activo` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_TELEFONO_USUARIO`
    FOREIGN KEY (`USUARIO_id`)
    REFERENCES `personal_management`.`USUARIO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `personal_management`.`RED_SOCIAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `personal_management`.`RED_SOCIAL` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `url` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `personal_management`.`PERFIL_SOCIAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `personal_management`.`PERFIL_SOCIAL` (
  `RED_SOCIAL_id` INT NOT NULL,
  `USUARIO_id` INT NOT NULL,
  `url_perfil` VARCHAR(45) NULL,
  PRIMARY KEY (`RED_SOCIAL_id`, `USUARIO_id`),
  CONSTRAINT `fk_RED_SOCIAL_has_USUARIO_RED_SOCIAL1`
    FOREIGN KEY (`RED_SOCIAL_id`)
    REFERENCES `personal_management`.`RED_SOCIAL` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RED_SOCIAL_has_USUARIO_USUARIO1`
    FOREIGN KEY (`USUARIO_id`)
    REFERENCES `personal_management`.`USUARIO` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
